name: Push checking CI

on:
  workflow_dispatch: { }
  push: { }
  pull_request: { }

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    environment: docker_check

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }} -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
