name: Docker Image CI

on:
  workflow_dispatch: { }

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    environment: docker_push

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username:  ${{ secrets.DOCKER_USER }}
        password:  ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker buildx build . -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }} -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
    - name: Push docker image
      run: docker image push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
    - name: push latest
      run: docker image push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
